CREATE TABLE `causes` ( `id` INT NOT NULL AUTO_INCREMENT , `name` TINYTEXT NOT NULL , `description` TEXT NOT NULL , `thumb` VARCHAR(100) NOT NULL , `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = MyISAM; 

CREATE TABLE `causes_images` ( `id` INT NOT NULL AUTO_INCREMENT , `cause_id` INT(10) NOT NULL , `name` VARCHAR(100) NOT NULL , `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = MyISAM; 


CREATE TABLE `requested_cause` ( `id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(100) NOT NULL ,  `cause` VARCHAR(100) NOT NULL , `email` VARCHAR(50) NULL , `phone` VARCHAR(50) NULL , `message` TINYTEXT NULL , `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = MyISAM; 